Protect form a large number of instances started simultaneously, Fix #14
OpenHFT/Chronicle-Analytics pull request #15
Opened 2022-03-24 14:35 UTC by minborg

2022-03-24 14:38 UTC, alamar requested changes

2022-03-24 14:38 UTC, alamar commented on src/main/java/net/openhft/chronicle/analytics/internal/AbstractGoogleAnalytics.java
> +    private final boolean createdSameAsLastUsedDileTimeStampSecond;
"FileTimeStamp"

2022-03-24 14:38 UTC, alamar commented on src/main/java/net/openhft/chronicle/analytics/internal/AbstractGoogleAnalytics.java
> +        if (createdSameAsLastUsedDileTimeStampSecond) {
I guess it should be checked here and not in constructor?

2022-03-24 14:38 UTC, alamar commented on src/main/java/net/openhft/chronicle/analytics/internal/FilesUtil.java
> +                "/.chronicle.analytics.last";
Makes sense to move to constant

2022-03-24 14:38 UTC, alamar commented on src/main/java/net/openhft/chronicle/analytics/internal/FilesUtil.java
> +    static boolean isNowSameAsLastUsedFileTimeStampSecond() {
Can we have more precise granularity - makes sense to just return second of day and compare outside this method.

2022-03-24 14:42 UTC, minborg commented on src/main/java/net/openhft/chronicle/analytics/internal/AbstractGoogleAnalytics.java
> +        if (createdSameAsLastUsedDileTimeStampSecond) {
No. It is checked at construction time. That way, only one instance on the machine will actually send data of those created in the same second.

2022-03-24 15:03 UTC, alamar approved these changes

2022-03-24 15:08 UTC, merged

2022-03-25 07:54 UTC, JerryShea commented on src/main/java/net/openhft/chronicle/analytics/internal/FilesUtil.java
> +    // Just for test purposes
`@TestOnly`